server:
  port: 8088
#   servlet:
#     session:
#       cookie:
#         name: BUSINESS-OAUTH2-CLIENT-SESSIONID

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream,refresh

spring:
  zipkin:
    baseUrl: http://zipkin/
  sleuth:
    sampler:
      probability: 1.0
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.BestAvailableRule
    ReadTimeout: 5000
    ConnectTimeout: 5000
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

logging:
  level:
    org.springframework.cloud: DEBUG

data:  
  env: data-refresh-test
  user:    
    username: test    
    password: 12345678
