server:
  port: 8088

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream,refresh

spring:
  zipkin:
    baseUrl: http://zipkin/
  sleuth:
    sampler:
      probability: 1.0
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.BestAvailableRule
    ReadTimeout: 5000
    ConnectTimeout: 5000
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  
  security:
    oauth2:
      client:
        userAuthorizationUri: http://localhost:8016/oauth/authorize
        accessTokenUri: http://localhost:8016/oauth/access_token
        clientAuthenticationScheme: form
      resource:
        userInfoUri: http://localhost:8016/user/info
        preferTokenInfo: false


logging:
  level:
    org.springframework.cloud: DEBUG

data:  
  env: data-refresh-test
  user:    
    username: test    
    password: 12345678
