server:
  port: 8014

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream,refresh

spring:
  zipkin:
    baseUrl: http://zipkin/
  sleuth:
    sampler:
      probability: 1.0
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  security:
    oauth2:
      client:
        userAuthorizationUri: http://localhost:8016/oauth/authorize
        accessTokenUri: http://localhost:8016/oauth/access_token
        clientAuthenticationScheme: form
      resource:
        userInfoUri: http://localhost:8016/user/info
        preferTokenInfo: false

logging:
  level:
    org.springframework.cloud: DEBUG
