server:
  port: 8084


eureka:
      client:
        registerWithEureka: false
        fetchRegistry: false

spring:
  zipkin:
    baseUrl: http://log/
  sleuth:
    sampler:
      probability: 1.0

logging:
  level:
    org.springframework.cloud: 'DEBUG'
