server:
  port: 8086

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8084/eureka/

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream

spring:
  zipkin:
    baseUrl: http://log/
  sleuth:
    sampler:
      probability: 1.0
  cloud:
    gateway:
      default-filters:
      routes:
        - id: my_route
          uri: lb://my-load-balanced-service
          predicates:
            - Path=/**
          filters:
            - StripPrefix=1

my-load-balanced-service:
  ribbon:
    listOfServers: localhost:1001, localhost:1002,localhost:1003
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule

logging:
  level:
    org.springframework.cloud: 'DEBUG'
