server:
  port: 8010

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8084/eureka/

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream,refresh

turbine:
  app-config: hystrix,log,gateway,config,business
  aggregator:
    cluster-config: default
  cluster-name-expression: new String("default")
  combine-host-port: true

spring:
  zipkin:
    baseUrl: http://log/
  sleuth:
    sampler:
      probability: 1.0
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest


logging:
  level:
    org.springframework.cloud: 'DEBUG'
