
server:
  port: 8012

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8084/eureka/

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream

spring:
  zipkin:
    baseUrl: http://log/

logging:
  level:
    org.springframework.cloud: 'DEBUG'
