server:
  port: 8016

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream,refresh

spring:
  zipkin:
    baseUrl: http://zipkin/
  sleuth:
    sampler:
      probability: 1.0

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

logging:
  level:
    org.springframework.cloud: DEBUG
