server:
  port: 8016

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8084/eureka/
spring:
  zipkin:
    baseUrl: http://zipkin/
  sleuth:
    sampler:
      probability: 1.0

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

logging:
  level:
    org.springframework.cloud: DEBUG
