server:
  port: 8010

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8084/eureka/

turbine:
  app-config: gateway,business,business2
  aggregator:
    cluster-config: default
  cluster-name-expression: new String("default")
  combine-host-port: true

spring:
  zipkin:
    baseUrl: http://log/
  sleuth:
    sampler:
      probability: 1.0

logging:
  level:
    org.springframework.cloud: DEBUG
