server:
  port: 8086
  servlet:
    session:
      cookie:
        name: OAUTH2-CLIENT-SESSIONID

management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  zipkin:
    baseUrl: http://zipkin/
    sender: 
      type: web
  sleuth:
    sampler:
      probability: 1.0
  redis:
    host: localhost
    port: 6379
    database: 0

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest


zuul:
  routes:
    business:
      path: /business/**
      sensitiveHeaders:
      serviceId: business
    business2:
      path: /business2/**
      sensitiveHeaders:
      serviceId: business2
  ratelimit:
    enabled: true
    repository: REDIS
    default-policy:
      limit: 3
      refresh-interval: 5
      type: origin


logging:
  level:
    org.springframework.cloud: DEBUG
