server:
  port: 8086
  servlet:
    session:
      cookie:
        name: ZUUL-OAUTH2-CLIENT-SESSIONID
management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  zipkin:
    baseUrl: http://zipkin/
  sleuth:
    sampler:
      probability: 1.0

zuul:
  sensitiveHeaders: Cookie,Set-Cookie,Authorization
  routes:
    business:
      path: /business/**
      serviceId: business
    business2:
      path: /business2/**
      serviceId: business2
  ratelimit:
    enabled: true
    repository: IN_MEMORY
    default-policy:
      limit: 3
      refresh-interval: 5
      type: origin

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest


logging:
  level:
    org.springframework.cloud: DEBUG
